const BASE_URL=((import.meta.env.VITE_API_BASE_URL as string|undefined)??'http://localhost:8000/api/v1').replace(/\/$/,'');
export class ApiError extends Error { readonly status:number; readonly code:string; constructor(status:number,code:string,message:string){super(message);this.name='ApiError';this.status=status;this.code=code;} get isQuotaExceeded():boolean{return this.status===402||this.code==='quota_exceeded'} get isUnauthorized():boolean{return this.status===401} get requiresPro():boolean{return this.status===403} }
interface ErrorBody { error?: {code?:string;message?:string} }
let accessToken:string|null=null; let refreshToken:string|null=null; let refreshing:Promise<boolean>|null=null;
export function setTokens(access:string,refresh:string):void{accessToken=access;refreshToken=refresh} export function clearTokens():void{accessToken=null;refreshToken=null} export function hasSession():boolean{return accessToken!==null}
async function parseError(response:Response):Promise<ApiError>{let code=`http_${response.status}`,message=response.statusText||'Request failed';try{const body=await response.json() as ErrorBody;code=body.error?.code??code;message=body.error?.message??message}catch{}return new ApiError(response.status,code,message)}
async function refreshSession():Promise<boolean>{if(refreshToken===null)return false;if(refreshing!==null)return refreshing;refreshing=(async()=>{try{const response=await fetch(`${BASE_URL}/auth/refresh`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({refresh_token:refreshToken})});if(!response.ok){clearTokens();return false}const data=await response.json() as {access_token:string;refresh_token:string};setTokens(data.access_token,data.refresh_token);return true}catch{return false}finally{refreshing=null}})();return refreshing}
interface RequestOptions { method?:'GET'|'POST'|'PATCH'|'DELETE';body?:unknown;formData?:FormData;signal?:AbortSignal;retryOnUnauthorized?:boolean }
export async function request<T>(path:string,options:RequestOptions={}):Promise<T>{const {method='GET',body,formData,signal,retryOnUnauthorized=true}=options;const headers:Record<string,string>={};if(accessToken!==null)headers.authorization=`Bearer ${accessToken}`;if(body!==undefined)headers['content-type']='application/json';const response=await fetch(`${BASE_URL}${path}`,{method,headers,body:formData??(body===undefined?undefined:JSON.stringify(body)),signal});if(response.status===401&&retryOnUnauthorized&&await refreshSession())return request<T>(path,{...options,retryOnUnauthorized:false});if(!response.ok)throw await parseError(response);if(response.status===204)return undefined as T;return await response.json() as T}
export const api={get:<T>(path:string,signal?:AbortSignal)=>request<T>(path,{signal}),post:<T>(path:string,body?:unknown)=>request<T>(path,{method:'POST',body}),patch:<T>(path:string,body:unknown)=>request<T>(path,{method:'PATCH',body}),del:<T>(path:string)=>request<T>(path,{method:'DELETE'}),upload:<T>(path:string,formData:FormData)=>request<T>(path,{method:'POST',formData})}; export {BASE_URL};
